spring:
  application:
    name: spring-ai-alibaba-dynamic-mcp-server-example
  ai:
    mcp:
      server:
        name: dynamic-mcp-server
        version: 1.0.0

    alibaba:
      mcp:
        nacos:
          server-addr: localhost:8848
          namespace: public
          username: nacos
          password:
          dynamic:
            enabled: true
            service-names: echo-server

server:
  port: 8090
