server:
  port: 10009

spring:
  application:
    name: spring-ai-alibaba-azure-openai-chat-model-example
  ai:
    azure:
      openai:
        api-key: ${AI_AZURE_OPENAI_API_KEY}
        endpoint: ${AI_AZURE_OPENAI_ENDPOINT}

