server:
  port: 10010

spring:
  application:
    name: spring-ai-alibaba-moonshot-chat-model-example

  ai:
    moonshot:
      api-key: ${MOONSHOT_API_KEY}
      base-url: "https://api.moonshot.cn"
      chat:
        options:
          model: moonshot-v1-8k
      embedding:
        enabled: false

