server:
  port: 10003

spring:
  application:
    name: spring-ai-alibaba-zhipuai-chat-model-example

  ai:
    zhipuai:
      api-key: ${ZHIPUAI_API_KEY}
      base-url: "https://open.bigmodel.cn/api/paas"
      chat:
        options:
          model: glm-4-flash
      embedding:
        enabled: false
